name: Drupal upgrade training config
type: module
description: Configuration for Drupal upgrade training. Created by Mauricio Dinarte (@dinarcon). https://understanddrupal.com
package: Migration
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - address:address
  - drupal:datetime
  - drupal:image
  - drupal:migrate
  - drupal:options
  - drupal:taxonomy
  - drupal:text
  - drupal:views
  - ud_drupal_upgrade:ud_drupal_upgrade_config
  - migrate_plus:migrate_plus
  - migrate_tools:migrate_tools
  - paragraphs:paragraphs
