name: Drupal upgrade training config
type: module
description: Configuration for Drupal upgrade training. Created by Mauricio Dinarte (@dinarcon). https://understanddrupal.com
package: Migration
core_version_requirement: ^9 || ^10 || ^11
dependencies:
  - address:address
  - drupal:datetime
  - drupal:image
  - drupal:migrate
  - drupal:options
  - drupal:taxonomy
  - drupal:text
  - drupal:views
  - migrate_plus:migrate_plus
  - paragraphs:paragraphs
  - social_link_field:social_link_field
